USE [SQLExample]
GO

/****** Object:  Table [dbo].[BIRIMLER]    Script Date: 10/11/2019 18:54:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BIRIMLER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BIRIM_ADI] [nvarchar](50) NULL,
 CONSTRAINT [PK_BIRIMLER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [SQLExample]
GO

/****** Object:  Table [dbo].[KULLANICILAR]    Script Date: 10/11/2019 18:54:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KULLANICILAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KULLANICI_ADI] [nvarchar](50) NULL,
	[KULLANICI_SIFRE] [nvarchar](50) NULL,
	[KULLANICI_KAYIT_TARIHI] [datetime] NULL,
	[KULLANICI_BIRIM_ID] [int] NULL,
 CONSTRAINT [PK_KULLANICILAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



